### ISSUE TITLE
Multivariant bundling seems hardcoded for specific languages

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-bundler#1]
The archive:

https://gtsvn.uit.no/divvun/artifacts/speller-crk_0.1.1-nightly.20201021T053453Z_mobile.txz

contains three bhfst files: `crk.bhfst, crk-x-macron.bhfst, crk-Cans.bhfst`

while the archive:

https://gtsvn.uit.no/divvun/artifacts/speller-nno_0.1.1-nightly.20201020T070259Z_mobile.txz

contains only one: `nn.bhfst`.

Expected two files: the above + `nn-Runr.bhfst`.

Thus it seems that the bundling of the crk alternatives is hardcoded, and not derived from the actual build result.

**Comment by bbqsrc** [comment]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/279099/97147856-78777900-176a-11eb-9530-49ed9f5a683f.png">


<img width="544" alt="image" src="https://user-images.githubusercontent.com/279099/97147831-6d244d80-176a-11eb-8fd2-cbb9004f4b55.png">
